# 允许鼠标支持
set -g mouse on

# 启用 vi 模式（Vim 风格的快捷键）
setw -g mode-keys vi

# 启用 256 色支持
set -g default-terminal "screen-256color"


# 窗格切换快捷键（Vim 风格）
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# 窗格大小调整
bind < resize-pane -L
bind > resize-pane -R
bind + resize-pane -U
bind - resize-pane -D

# 新建窗口继承路径
bind c new-window -c "#{pane_current_path}"

# 水平分割面板继承路径
bind '"' split-window -c "#{pane_current_path}"

# 垂直分割面板继承路径
bind % split-window -h -c "#{pane_current_path}"

# 开关tmux stats bar
bind-key S set-option status

# 自动重载 tmux 配置
bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"

# 将状态栏移动到屏幕顶部
set-option -g status-position top
set -g status-style "bg=terminal,fg=colour7" 
set -g status-left "#[bg=colour10,fg=colour0,bold] #S #[bg=default,fg=colour10] "
set -g status-left-length 20
setw -g window-status-format " #[fg=colour7]#I:#W "

setw -g window-status-current-format "#[fg=colour12,bg=colour8]#[fg=colour15,bg=colour12,bold] #I:#W #[fg=colour12,bg=default]"

set -g status-right-length 100
set -g status-right "#[fg=colour6]#[bg=colour6,fg=colour0] %Y-%m-%d #[fg=colour13,bg=colour6]#[bg=colour13,fg=colour0,bold] %H:%M:%S #[fg=colour15,bg=colour13]#[bg=colour15,fg=colour0] %a "

set -g message-style "bg=colour11,fg=colour0,bold" # 命令模式下的颜色
set -g pane-border-style "fg=colour8"              # 普通面板边框
set -g pane-active-border-style "fg=colour10"       # 活动面板边框（光标绿）

# 允许分离后保持会话
set -g detach-on-destroy off

# 新建窗口继承路径
bind c new-window -c "#{pane_current_path}"

# 水平分割面板继承路径
bind '"' split-window -c "#{pane_current_path}"

# 垂直分割面板继承路径
bind % split-window -h -c "#{pane_current_path}"
