windowrule = match:class ^(firefox|Navigator|google-chrome|Microsoft-edge)$, opacity 1.111 1.25 1.0 force
windowrule = match:class ^(firefox|Navigator|google-chrome|Microsoft-edge)$, no_blur on

windowrule = match:class ^(org.gnome.Showtime|mpv|vlc)$, opacity 1.111 1.25 1.0 force
windowrule = match:class ^(org.gnome.Showtime|mpv|vlc)$, no_blur on

windowrule = match:class ^(org.gnome.Loupe)$, opacity 1.111 1.25 1.0 force
windowrule = match:class ^(org.gnome.Loupe)$, no_blur on
