-- Hyprland configuration (Lua) — https://wiki.hypr.land/Configuring/Start/

hl.config({ autogenerated = false })

-- DMS_STARTUP_BEGIN // auto start
hl.on("hyprland.start", function()
	hl.exec_cmd("dbus-update-activation-environment --systemd --all")
	hl.exec_cmd("systemctl --user start hyprland-session.target")

	-- Start Fcitx5
	hl.exec_cmd("fcitx5 -d")
	-- Start Clash Verge
	hl.exec_cmd("clash-verge")
end)
-- DMS_STARTUP_END

hl.config({
	input = {
		-- empty inherits XKB_DEFAULT_LAYOUT (libxkbcommon), falls back to "us"
		kb_layout = "",
		numlock_by_default = true,
		follow_mouse = 0,
		touchpad = {
			tap_to_click = true,
			natural_scroll = true,
		},
	},
	general = {
		gaps_in = 5,
		gaps_out = 5,
		border_size = 2,
		layout = "scrolling",
	},

	scrolling = {
		direction = "right",

		fullscreen_on_one_column = true,
		column_width = 0.5,

		focus_fit_method = 1,
		follow_focus = true,
		follow_min_visible = 0.4,

		wrap_focus = true,
		wrap_swapcol = true,

		explicit_column_widths = "0.333, 0.5, 0.667, 1.0",
	},

	decoration = {
		rounding = 12,
		active_opacity = 0.88,
		inactive_opacity = 0.70,
		shadow = {
			enabled = true,
			range = 30,
			render_power = 5,
			offset = "0 5",
			color = "rgba(00000070)",
		},
	},
	misc = {
		disable_hyprland_logo = true,
		disable_splash_rendering = true,
	},
	dwindle = {
		preserve_split = true,
	},
	master = {
		mfact = 0.5,
	},
	xwayland = {
		force_zero_scaling = true,
	},
})

require("dms.colors")
require("dms.outputs")
require("dms.layout")
require("dms.cursor")
require("dms.binds")
require("dms.windowrules")
require("myconf.animation")
require("myconf.binds-user")
require("myconf.gesture")
require("myconf.window_rule")
require("myconf.layer_rule")
