[colors]
background = '#1e1e2e'
foreground = '#cdd6f4'

cursor_bg = '#74c7ec'
cursor_fg = '#1e1e2e'
cursor_border = '#74c7ec'

selection_bg = '#1f4d6f'
selection_fg = '#cdd6f4'

ansi = ['#181825', '#ff709e', '#74ec81', '#fff670', '#57b6e0', '#074d6d', '#74c7ec', '#e8f3f7']
brights = ['#8d9599', '#ff9dbd', '#a4ffae', '#fff9a4', '#90ddff', '#a4e3ff', '#c4edff', '#f8fcff']
